[package]
name = "mirai-jni-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.31"
mirai-jni-rs-macro = { path = "../mirai-jni-rs-macro" }
jni = "0.21.1"
